version: '3.8'
services:
    server:
        build: ./server
        environment:
            - TZ=America/Bahia
        ports:
            - "50051:50051"
        volumes:
            - ./server:/app
        restart: always
    client:
        build: ./client
        volumes:
            - ./client:/app
        restart: always
        depends_on:
            - server
    client2:
        build: ./client
        volumes:
            - ./client:/app
        restart: always
        depends_on:
            - server
